# Uso de throw

## Ejemplo 1

![](./snippets/throw.png)

En el primer ejemplo se utiliza un concepto llamado generadores. Los generadores son funciones especiales que pueden pausar su ejecuciÃ³n y luego continuarla mÃ¡s tarde. Se definen con el sÃ­mbolo * despuÃ©s de la palabra reservada function.

La funciÃ³n gen es un generador que entra en un bucle infinito. Dentro de este bucle, intenta producir (o "yield") el nÃºmero 42. Si no ocurre ninguna excepciÃ³n, seguirÃ¡ produciendo 42 indefinidamente cada vez que se le pida un nuevo valor.

Sin embargo, si se lanza una excepciÃ³n dentro del generador utilizando el mÃ©todo throw, el flujo de control se moverÃ¡ al bloque catch. En este caso, se registra el mensaje "Â¡Error detectado!" en la consola.

La variable g es una instancia del generador. Cuando se llama al mÃ©todo next en g, el generador produce su primer valor, que es 42. Este valor se devuelve en un objeto con la forma { value: 42, done: false }, donde value es el valor producido y done es un booleano que indica si el generador ha terminado de producir valores.

Luego, se lanza una excepciÃ³n en el generador utilizando el mÃ©todo throw. Esto causa que el generador capture la excepciÃ³n y registre el mensaje "Â¡Error detectado!". A pesar de la excepciÃ³n, el generador no se detiene y puede continuar produciendo valores. Por lo tanto, si se llama a g.next() de nuevo, se producirÃ¡ otro 42.

## Ejemplo 2

![](./snippets/throwObservable.png)

Este segundo ejemplo utiliza la biblioteca RxJS para trabajar con observables y promesas.

Primero, se crea una nueva promesa que realiza una solicitud HTTP a la URL 'http://httpstat.us/500' utilizando la funciÃ³n fetch. Si la solicitud es exitosa, se intenta convertir la respuesta en JSON con data.json(). Luego, se imprime en la consola 'Promesa resuelta' y se resuelve la promesa con los datos JSON. Si ocurre algÃºn error durante este proceso, se imprime en la consola 'Promesa rechazada' y se rechaza la promesa con el error.

DespuÃ©s, se crea un observable a partir de la promesa utilizando Rx.Observable.fromPromise(promesa). Un observable es un objeto que emite notificaciones (o eventos) a lo largo del tiempo. Puedes suscribirte a estos eventos utilizando el mÃ©todo subscribe.

Finalmente, se suscribe al observable. El mÃ©todo subscribe toma hasta tres argumentos: un manejador de Ã©xito, un manejador de error y un manejador de finalizaciÃ³n. En este caso, si el observable emite datos (es decir, si la promesa se resuelve con Ã©xito), se imprime 'resultados' junto con los datos. Si el observable emite un error (es decir, si la promesa se rechaza), se lanza el error.

![](./snippets/throwObservableResult.png)

> Si consideras Ãºtil esta informaciÃ³n, apÃ³yalo haciendo "â˜… Star" en el repositorio. Â¡Gracias ğŸ™Œ!
